@startuml useCase admin
!theme blueprint

skinparam actorStyle awesome
actor Administrateur as Admin
left to right direction

usecase "se connecter" as login
usecase "CRUD data" as CRUD
usecase "gestion des produits" as manageProducts
usecase "gestion des commandes" as manageOrders
usecase "gestion des clients" as manageCustomers

Admin --> login : <<include>>
Admin --> CRUD : <<authorize>>

CRUD --> manageProducts
CRUD --> manageOrders
CRUD --> manageCustomers

@enduml