services:
  frontend:
    image: axelvalentin/harmonyheaven:frontend-v1.0.8-2024-05-02
    ports:
      - "8080:8080"
    networks:
      - app_net

  backend:
    image: axelvalentin/harmonyheaven:backend-v1.0.7-2024-05-03
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - DATABASE_URL=mysql://41529f9a3cdd:-U%g}W(MJL2UFJLDGe:+@database:3306/harmonyheaven
    networks:
      - app_net
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: harmonyheaven
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_net
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password

  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app_net

secrets:
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

networks:
  app_net:

volumes:
  db-data:
    driver: local
