services:
  frontend:
    image: harmony-heaven-front:v1.1
    ports:
      - "5200:5200"
    networks:
      - app_net

  backend:
    image: axelvalentin/harmonyheaven:backend-1
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - DATABASE_URL=mysql://symfony_user:symfony_password@database:3306/symfony_db
    networks:
      - app_net
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_net
    secrets:
      - mysql_root_password
      - mysql_password

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app_net

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  app_net:

volumes:
  db-data:
    driver: local
