controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST

get-current-user:
  path: /get-current-user
  controller: App\Controller\LoginController::getCurrentUser
  methods: GET

register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

products-list:
  path: /products-list
  controller: App\Controller\ProductController::getProducts
  methods: GET

product-details:
  path: /product/{id}
  controller: App\Controller\ProductController::getProductById
  methods: GET

genres-list:
  path: /genres-list
  controller: App\Controller\GenreController::getGenres
  methods: GET

forgot-password:
  path: /forgot-password
  controller: App\Controller\ResetPasswordController::forgotPassword
  methods: POST

check-token:
  path: /check-token
  controller: App\Controller\ResetPasswordController::checkToken
  methods: POST

reset-password:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::resetPassword
  methods: POST

cart:
  path: /cart
  controller: App\Controller\CartController::submitCart
  methods: POST

cart_add:
  path: /add_cart
  controller: App\Controller\CartController::addToCart
  methods: POST

wishlist:
  path: /wishlist
  controller: App\Controller\WishlistController::addToWishlist
  methods: POST

wishlist_remove:
  path: /wishlist/{productId}
  controller: App\Controller\WishlistController::removeFromWishlist
  methods: DELETE

get_wishlist:
  path: /get_wishlist
  controller: App\Controller\WishlistController::getWishlist
  methods: GET

order:
  path: /order
  controller: App\Controller\CartController::order
  methods: POST

UpdateUserBoardInformation:
  path: /user/board
  controller: App\Controller\UserBoardController::UpdateUserBoardInformation
  methods: PUT

ManageUsersInformations:
  path: /admin/board
  controller: App\Controller\AdminBoardController::ManageUsersInformations
  methods: PUT
