controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST

get-current-user:
  path: /get-current-user
  controller: App\Controller\LoginController::getCurrentUser
  methods: GET

register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

products-list:
  path: /products-list
  controller: App\Controller\ProductController::getProducts
  methods: GET

product-details:
  path: /product/{id}
  controller: App\Controller\ProductController::getProductById
  methods: GET

genres-list:
  path: /genres-list
  controller: App\Controller\GenreController::getGenres
  methods: GET

forgot-password:
  path: /forgot-password
  controller: App\Controller\ResetPasswordController::forgotPassword
  methods: POST

check-token:
  path: /check-token
  controller: App\Controller\ResetPasswordController::checkToken
  methods: POST

reset-password:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::resetPassword
  methods: POST

update-stock:
  path: /update-stock
  controller: App\Controller\CartController::updateStock
  methods: POST

increment-stock:
  path: /increment-stock
  controller: App\Controller\CartController::incrementStock
  methods: POST

decrement-stock:
  path: /decrement-stock
  controller: App\Controller\CartController::decrementStock
  methods: POST

submit-cart:
  path: /submit-cart
  controller: App\Controller\CartController::submitCart
  methods: POST

add-to-cart:
  path: /add-to-cart
  controller: App\Controller\CartController::addToCart
  methods: POST

update-cart-item:
  path: /update-cart-item/{productId}
  controller: App\Controller\CartController::updateCartItem
  methods: PUT

get-cart:
  path: /get-cart
  controller: App\Controller\CartController::getCart
  methods: GET

remove-from-cart:
  path: /remove-from-cart/{productId}
  controller: App\Controller\CartController::removeFromCart
  methods: DELETE

wishlist:
  path: /wishlist
  controller: App\Controller\WishlistController::addToWishlist
  methods: POST

wishlist_remove:
  path: /wishlist/{productId}
  controller: App\Controller\WishlistController::removeFromWishlist
  methods: DELETE

get_wishlist:
  path: /get_wishlist
  controller: App\Controller\WishlistController::getWishlist
  methods: GET

order:
  path: /order
  controller: App\Controller\CartController::order
  methods: POST

# USER BOARD

get-order:
  path: /get-order
  controller: App\Controller\CartController::getOrder
  methods: GET

UpdateUserBoardInformation:
  path: /user/board
  controller: App\Controller\UserBoardController::UpdateUserBoardInformation
  methods: PUT

pay:
  path: /pay
  controller: App\Controller\PaymentController::pay
  methods: POST

update-statuts:
  path: /update-statuts/{idOrder}
  controller: App\Controller\PaymentController::updateStatuts
  methods: POST

deleteUserAccount:
  path: /user/board/{id}
  controller: App\Controller\UserBoardController::deleteUserAccount
  methods: DELETE

# ADMIN

getAllProducts:
  path: /admin/products
  controller: App\Controller\AdminBoardController::getAllProducts
  methods: GET

updateProductsInformation:
  path: /admin/products/{id}
  controller: App\Controller\AdminBoardController::updateProductsInformation
  methods: PUT

deleteProduct:
  path: /admin/products/{id}
  controller: App\Controller\AdminBoardController::deleteProduct
  methods: DELETE

createProduct:
  path: /admin/products
  controller: App\Controller\AdminBoardController::createProduct
  methods: POST

getAllUsers:
  path: /admin/users
  controller: App\Controller\AdminBoardController::getAllUsers
  methods: GET

getUserById:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::getUserById
  methods: GET

updateUserInformation:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::updateUserInformation
  methods: PUT

deleteUser:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::deleteUser
  methods: DELETE
