controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST

get-current-user:
  path: /get-current-user
  controller: App\Controller\LoginController::getCurrentUser
  methods: GET

register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

products-list:
  path: /products-list
  controller: App\Controller\ProductController::getProducts
  methods: GET

product-details:
  path: /product/{id}
  controller: App\Controller\ProductController::getProductById
  methods: GET

genres-list:
  path: /genres-list
  controller: App\Controller\GenreController::getGenres
  methods: GET

forgot-password:
  path: /forgot-password
  controller: App\Controller\ResetPasswordController::forgotPassword
  methods: POST

check-token:
  path: /check-token
  controller: App\Controller\ResetPasswordController::checkToken
  methods: POST

reset-password:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::resetPassword
  methods: POST

cart:
  path: /cart
  controller: App\Controller\CartController::submitCart
  methods: POST

wishlist:
  path: /wishlist
  controller: 'App\Controller\WishlistController::addToWishlist'
  methods: POST

wishlist_remove:
  path: /wishlist/{productId}
  controller: 'App\Controller\WishlistController::removeFromWishlist'
  methods: DELETE

get_wishlist:
  path: /get_wishlist
  controller: 'App\Controller\WishlistController::getWishlist'
  methods: GET

order:
  path: /order
  controller: App\Controller\CartController::order
  methods: POST

# USER BOARD

UpdateUserBoardInformation:
  path: /user/board
  controller: App\Controller\UserBoardController::UpdateUserBoardInformation
  methods: PUT

deleteUserAccount:
  path: /user/board/{id}
  controller: App\Controller\UserBoardController::deleteUserAccount
  methods: DELETE

# ADMIN

getAllProducts:
  path: /admin/products
  controller: App\Controller\AdminBoardController::getAllProducts
  methods: GET

updateProductsInformation:
  path: /admin/products/{id}
  controller: App\Controller\AdminBoardController::updateProductsInformation
  methods: PUT

deleteProduct:
  path: /admin/products/{id}
  controller: App\Controller\AdminBoardController::deleteProduct
  methods: DELETE

createProduct:
  path: /admin/products
  controller: App\Controller\AdminBoardController::createProduct
  methods: POST

getAllUsers:
  path: /admin/users
  controller: App\Controller\AdminBoardController::getAllUsers
  methods: GET

getUserById:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::getUserById
  methods: GET

updateUserInformation:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::updateUserInformation
  methods: PUT

deleteUser:
  path: /admin/users/{id}
  controller: App\Controller\AdminBoardController::deleteUser
  methods: DELETE
