controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: POST

get-current-user:
  path: /get-current-user
  controller: App\Controller\LoginController::getCurrentUser
  methods: POST

register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

products-list:
  path: /products-list
  controller: App\Controller\ProductController::getProducts
  methods: GET

genres-list:
    path: /genres-list
    controller: App\Controller\GenreController::getGenres
    methods: GET

forgot-password:
    path: /forgot-password
    controller: App\Controller\ResetPasswordController::forgotPassword
    methods: POST

check-token:
    path: /check-token
    controller: App\Controller\ResetPasswordController::checkToken
    methods: POST

reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::resetPassword
    methods: POST

cart:
  path: /cart
  controller: App\Controller\CartController::submitCart
  methods: POST
