
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n
  .use(initReactI18next)
  .init({
    lng: navigator.language,
    resources: {
      en: {
        translation: {
        "NEWS & HOT": "NEWS & HOT",
        "EXCEPTIONAL":"EXCEPTIONAL",
        "VINYLS":"VINYLS", 
        "HARMONY":"HARMONY",
        "HEAVEN":"HEAVEN",
        "Contact Us":"Contact Us",
        "Name":"Name",
        "Newsletter":"Newsletter",
        "Subscribe":"Subscribe",
        "Enter your email":"Enter your email",
        "By subscribing you agree to with our":"By subscribing you agree to with our",
        "Privacy Policy":"Privacy Policy",
        "home":"Home",
        "Home":"Home",
        "contact":"contact",
        "Contact":"Contact",
        "CONTACT":"CONTACT",
        "Term of Service":"Term of Service",
        "Cookie Settings":"Cookie Settings",
        "All rights reserved.":"All rights reserved.",
        "LOGOUT":"LOGOUT",
        "Logout":"Logout",
        "LOGIN":"LOGIN",
        "REGISTER":"REGISTER",
        "ABOUT":"ABOUT",
        "profil":"PROFIL",
        "Wishlist":"Wishlist",
        "orders":"Orders",
        "Orders":"Orders",
        "shop":"Shop",
        "close":"close",
        "Add to Cart":"Add to Cart",
        "Delete account":"Delete account",
        "Delete my account":"Delete my account",
        "Delete your account":"Delete your account",
        "My profile":"My profil",
        "Personal informations":"Personal informations",
        "Update your personal informations":"Update your personal informations",
        "Check your orders":"Check your orders",
        "Payment Methods":"Payment Methods",
        "Add or remove payment methods":"Add or remove payment methods",
        "Print a bill":"Print a bill",
        "Print your bill":"Print your bill",
      },
    },
    fr: {
      translation: {
        "NEWS & HOT": "NOUVEAUTÉ & MEILLEURES VENTES",
        "EXCEPTIONAL":"VINYLE",
        "VINYLS":"D'EXCEPTION",
        "HARMONY":"HARMONY",
        "HEAVEN":"HEAVEN",
        "Contact Us":"Nous contacter",
        "Name":"Nom",
        "Newsletter":"Newsletter",
        "Subscribe":"S'abonner",
        "Enter your email":"Entrez votre email",
        "By subscribing you agree to with our":"En vous abonnant, vous acceptez notre",
        "Privacy Policy":"politique de confidentialité",
        "home":"Accueil",
        "Home":"Accueil",
        "contact":"contacte",
        "Contact":"Contacte",
        "CONTACT":"CONTACTE",
        "Term of Service":"Conditions d'utilisation",
        "Cookie Settings":"Paramètres des Cookies",
        "All rights reserved.":"Tous droits réservés",
        "LOGOUT":"DÉCONNEXION",
        "Logout":"Déconnexion",
        "LOGIN":"CONNEXION",
        "REGISTER":"INSCRIPTION",
        "about":"À PROPOS",
        "profil":"profile",
        "Wishlist":"liste de souhait",
        "orders":"commandes",
        "Orders":"Commandes",
        "shop":"Boutique",
        "close":"fermer",
        "Add to Cart":"Ajouter au panier",
        "Delete account":"Supprimer le compte",
        "Delete my account":"Delete mon account",
        "Delete your account":"Supprimer votre compte",
        "My profil":"Mon profile",
        "Personal informations":"Informations personnelles",
        "Update your personal informations":"Mettez à jour vos informations personnelles",
        "Check your orders":"Vérifier vos commandes",
        "Payment Methods":"Méthodes de payement",
        "Add or remove payment methods":"Ajouter ou supprimer des méthodes de payement",
        "Print a bill":"Imprimer une facture",
        "Print your bill":"Imprimer votre facture",

      },
    },
  },
});

export default i18n;
