<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Style;

class StyleFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $styles = [
            "Blues Rock",
            "Rhythm & Blues",
            "Rock & Roll",
            "Electric Blues",
            "Country Blues",
            "Chicago Blues",
            "Soul",
            "Pop Rock",
            "Classic Rock",
            "Folk",
            "Vocal",
            "Psychedelic Rock",
            "Folk Rock",
            "Piano Blues",
            "Delta Blues",
            "Modern Electric Blues",
            "Ballad",
            "Country Rock",
            "Country",
            "Acoustic",
            "Gospel",
            "Swing",
            "Hard Rock",
            "Harmonica Blues",
            "Alternative Rock",
            "Texas Blues",
            "Jump Blues",
            "Garage Rock",
            "Funk",
            "Doo Wop",
            "Louisiana Blues",
            "SoulJazz",
            "Southern Rock",
            "Boogie Woogie",
            "Rockabilly",
            "Experimental",
            "Easy Listening",
            "Big Band",
            "Indie Rock",
            "Soundtrack",
            "Soft Rock",
            "Prog Rock",
            "JazzRock",
            "Chanson",
            "Punk",
            "Beat",
            "Dixieland",
            "Avantgarde",
            "Bluegrass",
            "Contemporary Jazz",
            "Ragtime",
            "Fusion",
            "Synthpop",
            "Holiday",
            "Disco",
            "Jazz-Funk",
            "LoFi",
            "Memphis Blues",
            "East Coast Blues",
            "Art Rock",
            "Downtempo",
            "Cool Jazz",
            "Smooth Jazz",
            "Bop",
            "Stoner Rock",
            "African",
            "Surf",
            "Piedmont Blues",
            "Mod",
            "New Wave",
            "Ambient",
            "Ska",
            "Heavy Metal",
            "Cajun",
            "Zydeco",
            "Free Improvisation",
            "Electro",
            "Abstract",
            "Instrumental",
            "Acid Rock",
            "House",
            "Bayou Funk",
            "Indie Pop",
            "Europop",
            "Schlager",
            "Arena Rock",
            "Pub Rock",
            "Noise",
            "Psychedelic",
            "Contemporary R&B",
            "Spoken Word",
            "Neo Soul",
            "Latin Jazz",
            "Theme",
            "Honky Tonk",
            "Reggae",
            "Pop Rap",
            "Score",
            "RnBSwing",
            "Glam",
            "Power Pop",
            "Hard Bop",
            "Twist",
            "Novelty",
            "Parody",
            "Comedy",
            "AOR",
            "Hip Hop",
            "Field Recording",
            "Free Jazz",
            "Lounge",
            "Classical",
            "Public Broadcast",
            "Swamp Pop",
            "Trip Hop",
            "Religious",
            "Bossa Nova",
            "Interview",
            "Space Rock",
            "PostPunk",
            "Post Bop",
            "Post Rock",
            "Industrial",
            "Calypso",
            "Dub",
            "Dancepop",
            "Musical",
            "Celtic",
            "Avantgarde Jazz",
            "Contemporary",
            "Western Swing",
            "Jug Band",
            "Tango",
            "Hillbilly",
            "Afrobeat",
            "Samba",
            "Grunge",
            "Poetry",
            "Psychobilly",
            "Symphonic Rock",
            "Skiffle",
            "Krautrock",
            "MPB",
            "Hill Country Blues",
            "Techno",
            "Doom Metal",
            "ReggaePop",
            "Mambo",
            "Neofolk",
            "ChaCha",
            "Conscious",
            "Romantic",
            "Flamenco",
            "Leftfield",
            "Boogie",
            "Gypsy Jazz",
            "Bolero",
            "Breakbeat",
            "AfroCuban Jazz",
            "Hardcore",
            "Euro House",
            "Appalachian Music",
            "Drone",
            "Acid Jazz",
            "Minimal",
            "New Age",
            "Rumba",
            "Latin",
            "Goth Rock",
            "Bossanova",
            "Jpop",
            "Future Jazz",
            "Modern Classical",
            "AfroCuban",
            "Modern",
            "Modal",
            "Thrash",
            "Jazzy Hip-Hop",
            "Drum n Bass",
            "Education",
            "Dialogue",
            "Light Music",
            "Free Funk",
            "Shoegaze",
            "SpaceAge",
            "Polka",
            "Trance",
            "Brass Band",
            "Stride",
            "Ethereal",
            "Funk Metal",
            "Kaykyoku",
            "Deep House",
            "Music Hall",
            "NeoClassical",
            "Black Metal",
            "Britpop",
            "Pop Punk",
            "Rocksteady",
            "Spirituals",
            "Dark Ambient",
            "Salsa",
            "Pacific",
            "IDM",
            "Cumbia",
            "Gangsta",
            "Big Beat",
            "Breaks",
            "Eurodance",
            "Political",
            "Opera",
            "Roots Reggae",
            "Freestyle",
            "Speech",
            "Swingbeat",
            "Volksmusik",
            "ntekhno",
            "Hawaiian",
            "Cut-up/DJ",
            "Darkwave",
            "Death Metal",
            "Highlife",
            "Conjunto",
            "Erotic",
            "Nordic",
            "Electro House",
            "Sermon",
            "Emo",
            "Baroque",
            "Boom Bap",
            "PFunk",
            "Acid",
            "Tejano",
            "Musique Concrte",
            "New Jack Swing",
            "Indian Classical",
            "Cantopop",
            "YY",
            "Canzone Napoletana",
            "Thug Rap",
            "Griot",
            "Radioplay",
            "No Wave",
            "Sludge Metal",
            "Cubano",
            "Mariachi",
            "Marches",
            "Choral",
            "Dubstep",
            "Hardcore Hip-Hop",
            "Progressive House",
            "Broken Beat",
            "Tribal",
            "Promotional",
            "Klezmer",
            "Monolog",
            "Bubblegum",
            "Nu Metal",
            "Dancehall",
            "Bass Music",
            "Aboriginal",
            "ItaloDisco",
            "Jazzdance",
            "Chillwave",
            "Garage House",
            "Horror Rock",
            "Tech House",
            "Math Rock",
            "Ragga HipHop",
            "Technical",
            "Dream Pop",
            "Lak",
            "Special Effects",
            "Acid House",
            "Boogaloo",
            "Kpop",
            "Glitch",
            "Mandopop",
            "Cabaret",
            "Romani",
            "GoGo",
            "Educational",
            "Progressive Metal",
            "JRock",
            "UK Garage",
            "HipHouse",
            "Pachanga",
            "Phleng Phuea Chiwit",
            "Rebetiko",
            "Grindcore",
            "Enka",
            "Impressionist",
            "Ranchera",
            "Story",
            "City Pop",
            "Nhc Vng",
            "Son",
            "Anison",
            "Sea Shanties",
            "Synthwave",
            "Bollywood",
            "Merengue",
            "Sound Art",
            "Beguine",
            "Jungle",
            "Nursery Rhymes",
            "Rhythmic Noise",
            "Chiptune",
            "Ethnopop",
            "Fado",
            "PostModern",
            "Power Metal",
            "Barbershop",
            "Zouk",
            "Minneapolis Sound",
            "Movie Effects",
            "Karaoke",
            "Norteo",
            "Audiobook",
            "Hi NRG",
            "NeoRomantic",
            "Sga",
            "Therapy",
            "AltPop",
            "Catalan Music",
            "Ragga",
            "Speed Metal",
            "Corrido",
            "EBM",
            "Medieval",
            "NuDisco",
            "Soca",
            "Sound Collage",
            "Renaissance",
            "Rock Opera",
            "Vaporwave",
            "Video Game Music",
            "Trap",
            "Vaudeville",
            "EuroDisco",
            "Ra",
            "Folk Metal",
            "KRock",
            "Public Service Announcement",
            "Soukous",
            "Beatbox",
            "GFunk",
            "Grime",
            "Hindustani",
            "Metalcore",
            "Deathrock",
            "Mento",
            "Sound Poetry",
            "Lovers Rock",
            "Progressive Bluegrass",
            "Andean Music",
            "Baio",
            "Italodance",
            "Pipe & Drum",
            "Reggaeton",
            "Miny",
            "Pasodoble",
            "Progressive Trance",
            "Salegy",
            "Cape Jazz",
            "Eurobeat",
            "Happy Hardcore",
            "Electroacoustic",
            "Maloya",
            "Cloud Rap",
            "Gothic Metal",
            "New Beat",
            "Operetta",
            "PostHardcore",
            "Power Electronics",
            "Alternative Metal",
            "Bounce",
            "Guaracha",
            "Reggae Gospel",
            "Breakcore",
            "Danzon",
            "Dark Jazz",
            "Dub Techno",
            "Electro Swing",
            "Hard Trance",
            "Lambada",
            "Latin Pop",
            "Nueva Cancion",
            "PsyTrance",
            "Son Montuno",
            "Turntablism",
            "Basque Music",
            "Descarga",
            "Group Sounds",
            "Guaguanc",
            "Neo Trance",
            "Tribal House",
            "BerlinSchool",
            "Choro",
            "Coldwave",
            "Illbient",
            "Jangle Pop",
            "Charanga",
            "Bachata",
            "Bassline",
            "Crunk",
            "Crust",
            "Guajira",
            "Hard House",
            "Hokkien Pop",
            "Military",
            "Oi",
            "Quechua",
            "Tropical House",
            "Compas",
            "Doomcore",
            "Early",
            "Electroclash",
            "Forr",
            "Melodic Death Metal",
            "Milonga",
            "Bhangra",
            "Chinese Classical",
            "Ghetto",
            "Groove Metal",
            "Horrorcore",
            "Levenslied",
            "Noise Rock",
            "Baroque Pop",
            "Candombe",
            "Chacarera",
            "Industrial Metal",
            "Juke",
            "NDW",
            "Persian Classical",
            "Rykka",
            "Viking Metal",
            "Bakersfield Sound",
            "Marimba",
            "Mbalax",
            "Melodic Hardcore",
            "Mouth Music",
            "Trova",
            "Batucada",
            "Dangdut",
            "Deep Techno",
            "Exotica",
            "Minimal Techno",
            "Ottoman Classical",
            "SambaCano",
            "Tech Trance",
            "Witch House",
            "Atmospheric Black Metal",
            "DJ Battle Tool",
            "Npzene",
            "Screw",
            "Sephardic",
            "Speedcore",
            "Symphonic Metal",
            "Ax",
            "BreakIn",
            "Carnatic",
            "Gabber",
            "Hardstyle",
            "Harsh Noise Wall",
            "IndoPop",
            "Keroncong",
            "Noisecore",
            "Occitan",
            "Speed Garage",
            "Steel Band",
            "Vallenato",
            "Andalusian Classical",
            "Ballroom",
            "Beatdown",
            "Gamelan",
            "Goa Trance",
            "Hard Techno",
            "Serial",
            "Sonero",
            "UK Funky",
            "Ghazal",
            "Junkanoo",
            "Kizomba",
            "Liscio",
            "Mizrahi",
            "Morna",
            "No Kyma",
            "Occult",
            "Overtone Singing",
            "PostMetal",
            "Russian Pop",
            "Balearic",
            "Chamam",
            "Cretan",
            "Funeral Doom Metal",
            "Gaita",
            "Italo House",
            "Joropo",
            "Musette",
            "Rune Singing",
            "Schranz",
            "Timba",
            "UK Street Soul",
            "Banda",
            "Bengali Music",
            "Crossover thrash",
            "Dub Poetry",
            "Favela Funk",
            "Filk",
            "Funkot",
            "Gagaku",
            "Hands Up",
            "Jibaro",
            "Kwaito",
            "Makina",
            "Msica Criolla",
            "Neopagan",
            "Porro",
            "Qawwali",
            "Slowcore",
            "Smi Music",
            "Technical Death Metal",
            "Twelvetone",
            "Waiata",
            "Azonto",
            "Bitpop",
            "Bongo Flava",
            "Champeta",
            "Copla",
            "Donk",
            "French House",
            "Galician Traditional",
            "Glitch Hop",
            "Goregrind",
            "Gwo Ka",
            "HealthFitness",
            "Hiplife",
            "Hyphy",
            "Hypnagogic pop",
            "Medical",
            "Organ",
            "Philippine Classical",
            "Pornogrind",
            "Power Violence",
            "Zemer Ivri",
            "Amapiano",
            "Ballet",
            "Baltimore Club",
            "Bangladeshi Classical",
            "Blackgaze",
            "Brit Pop",
            "Caipira",
            "Chutney",
            "Comfy Synth",
            "Cuatro",
            "Deconstructed Club",
            "Depressive Black Metal",
            "Future House",
            "Future Pop",
            "Geet",
            "Ghettotech",
            "Gogo",
            "Guarania",
            "Hard Beat",
            "JCore",
            "Jersey Club",
            "Jumpstyle",
            "Kaseko",
            "Klasik",
            "Kolo",
            "Miami Bass",
            "PostGrunge",
            "Progressive Breaks",
            "Rapso",
            "Seresta",
            "Sunshine Pop",
            "Taarab",
            "Vpop",
            "Yemenite Jewish"
        ];

        foreach ($styles as $styleName) {
            $entity = new Style();
            $entity->setName($styleName);
            $manager->persist($entity);
        }
        $manager->flush();
    }
}
