@startuml class diagram

skin rose
!theme blueprint

left to right direction

title Classes - Class Diagram

class user {
    + id
    + name
    + email
    + password
    + phone
    + role
}

class product {
    + id
    + name
    + description
    + price
    + image
    + seller
    + slug
    + quantity

}

class category {
    + id
    + name
}

class subcategory {
    + category_id
    + id
    + name
}

class cart {
    + id
    + user_id
    + quantity
}

class cart_item {
    + id
    + cart_id
    + product_id
}

class order {
    + id
    + user_id
    + total
}

class order_item {
    + id
    + order_id
    + product_id
    + quantity
}

class receipt{
    +id
    +price
    +name
    +delivery
    +payment
    +product
    +date
}

class payment_method {
    + id
    + order_id
    + payment_method
}

class payment {
    + id
    + order_id
}

class delivery {
    + id
    + order_id
    + delivery_method
    + command_date 
    + delivery_date
    + UUID4
}

class deliveryInformation {
    + id
    + order_id
    + name
    + address
}

user "1" -- "0..1" cart
user "1" -- "0..*" order
order "1" -- "1" order_item
order "1..*" -- "1..*" delivery
delivery "1..*" -- "1" deliveryInformation
payment_method "1..*" -- "1" order
payment "1" -- "1" payment_method
product "1..*" -- "1..*" category
product "0..*" -- "1..*" cart
category "1" -- "0..*" subcategory
cart_item "1" -- "1" order_item
cart "1" -- "*" cart_item
receipt "1" -- "1" order

@enduml