@startuml class diagram

skin rose
!theme blueprint


title Class Diagram - Harmony Heaven Ecommerce

class User {
    + String name
    + String email
    + String password
    + String address
    + String phone
    + String role
}

class Product {
    + String name
    + String description
    + Float price
    + String image
    + String type
    + String label
    + String year
    + String country
    + String format
    + List <Genre> genres
    + List <Style> styles
}

class Genre {
    + String name
    + String description
}

class Style {
    + String name
    + String description
}

class Cart {
    + User user
    + List<CartItem> items
}

class CartItem {
    + Product product
    + int quantity
}

class Command {
    + User user
    + List<CommandItem> items
    + Payment payment
    + Delivery delivery
}

class CommandItem {
    + Product product
    + int quantity
}

class Receipt {
    + Command command
    + String receiptNumber

}

class PaymentMethod {
    + String name
    + String description
}

class Payment {
    + PaymentMethod method
    + String status
}

class Delivery {
    + String address
    + String status
}

class DeliveryInformation {
    + Delivery delivery
    + String trackingDetails
}

User "1" *-- "1" Cart : has  
'Un utilisateur a un panier (relation un-à-un)

Cart "1" *-- "*" CartItem : contains  
'Un panier peut contenir plusieurs articles (relation un-à-plusieurs)

User "1" *-- "*" Command : places 
'Un utilisateur peut passer plusieurs commandes (relation un-à-plusieurs)

Command "1" *-- "*" CommandItem : contains 
'Une commande peut contenir plusieurs articles (relation un-à-plusieurs)

Command "1" -- "1" Delivery : is delivered by 
'Une commande est livrée par une livraison (relation un-à-un)

Receipt "1" -- "1" Command : is for 
'Un reçu est pour une commande (relation un-à-un)

Command "1" -- "1" Payment : pays with 
'Une commande est payée avec un paiement (relation un-à-un)

Payment "1" -- "1" PaymentMethod : uses  
'Un paiement utilise une méthode de paiement (relation un-à-un)

Delivery "1" -- "1" DeliveryInformation : has  
 'Une livraison a des informations de livraison (relation un-à-un)

CartItem "1" -- "1" Product : is for 
'Un CartItem est pour un Product (relation un-à-un)

CommandItem "1" -- "1" Product : is for 
'Un commandItem est pour un Product (relation un-à-un)

Product "*" -- "*" Genre : has  
'Un produit peut avoir plusieurs genres et un genre peut appartenir à plusieurs produits (relation plusieurs-à-plusieurs)

Product "*" -- "*" Style : has  
'Un produit peut avoir plusieurs styles et un style peut appartenir à plusieurs produits (relation plusieurs-à-plusieurs)
@enduml